name: Deploy using CodeDeploy
on:
  workflow_dispatch:     

env:
  BUCKET_NAME: uda-164024806834-bucket

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    # Simulate a Deployment
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Create CloudFormation Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: udatest
        template: udatest.yml
        no-fail-on-empty-changeset: "1"
    
    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy push \
          --application-name YourApplicationName \
          --s3-location s3://YourBucketName/YourApplicationName.zip \
          --ignore-hidden-files

        aws deploy create-deployment \
          --application-name YourApplicationName \
          --s3-location bucket=YourBucketName,bundleType=zip,key=YourApplicationName.zip \
          --deployment-group-name YourDeploymentGroupName \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --description "My GitHub Action Deployment"



          